{
 "title": "pc scrivania",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "GPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_load_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_temperature_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Consumption",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_power_draw_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_fan_speed_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU VRAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_memory_usage_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "GPU Clocks",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_core_clock_0\" or r[\"_field\"] == \"gpu_memory_clock_0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 20, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\r\n  |> last(column: \"_time\")\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Current usage of CPU",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_total_usage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Physical Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_physical_cores\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_total_cores\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_max_frequency\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "PC General Info",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ip_address\" or r[\"_field\"] == \"mac_address\" or r[\"_field\"] == \"machine\" or r[\"_field\"] == \"pc_name\" or r[\"_field\"] == \"processor\" or r[\"_field\"] == \"release\" or r[\"_field\"] == \"system\" or r[\"_field\"] == \"version\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "GPU Generic Info",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gpu_memory_total_0\" or r[\"_field\"] == \"gpu_driver_version_0\" or r[\"_field\"] == \"gpu_name_0\" or r[\"_field\"] == \"gpu_power_limit_0\" or r[\"_field\"] == \"gpu_serial_0\" or r[\"_field\"] == \"gpu_uuid_0\" or r[\"_field\"] == \"gpu_vbios_version_0\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_percentage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RAM available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_available\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ram_total\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Used space on disk",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_percentage\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_free\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk total space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allPcStats\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"source\"] == \"pcScrivania\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_total_size\")\r\n  |> unique()\r\n  |> yield(name: \"unique\")"
    }
   ]
  }
 ]
}